package com.ahana.api.common;

public final class ErrorConstants {

//APPLICATION ERROR START//
public static final String SERVICE_NOT_AVAILABLE = "SERVICE NOT AVAILABLE"; 
public static final String SERVICE_NOT_ENABLED = "SERVICE NOT ENABLED"; 
public static final String SESSION_EXPIRED = "SESSION EXPIRED"; 
public static final String ACCESS_DENIED = "ACCESS DENIED"; 
public static final String GET_METHOD_NOT_SUPPORTED = "GET METHOD NOT SUPPORTED"; 
public static final String POST_METHOD_NOT_SUPPORTED = "POST METHOD NOT SUPPORTED"; 
	
	//APPLICATION ERROR END//
//SYSTEM ERROR START//
	
	//SYSTEM ERROR END//	
//BUSINESS ERROR START//
public static final String USER_NOT_FOUND = "USER NOT FOUND"; 
public static final String USER_INFORMATION_NOT_FOUND = "USER INFORMATION NOT FOUND"; 
public static final String USER_COULD_NOT_BE_SAVED = "USER COULD NOT BE SAVED"; 
public static final String UPDATE_PASSWORD_FAILED = "UPDATE PASSWORD FAILED"; 
public static final String INVALID_STATE_CODE = "INVALID STATE CODE"; 
public static final String INVALID_COUNTRY_CODE = "INVALID COUNTRY CODE"; 
public static final String NO_SEARCH_FOUND = "NO SEARCH FOUND"; 
public static final String NO_INFORMATION_FOUND_FOR_THIS_DOMAIN_OBJECT = "NO INFORMATION FOUND FOR THIS DOMAIN OBJECT"; 
public static final String INVALID_SEARCH_STRING_LENGTH = "INVALID SEARCH STRING LENGTH"; 
public static final String ZIP_CODE_IS_INVALID_LENGTH = "ZIP CODE IS INVALID LENGTH"; 
public static final String ZIP_CODE_IS_INVALID_FORMAT = "ZIP CODE IS INVALID FORMAT"; 
public static final String ZIP_CODE_IS_REQUIRED = "ZIP CODE IS REQUIRED"; 
public static final String NO_RECORDS_FOUND = "NO RECORDS FOUND"; 
public static final String OBJECT_NOT_FOUND = "OBJECT NOT FOUND"; 
public static final String FIRST_NAME_IS_REQUIRED = "FIRST NAME IS REQUIRED"; 
public static final String FIRST_NAME_IS_INVALID_LENGTH = "FIRST NAME IS INVALID LENGTH"; 
public static final String FIRST_NAME_MUST_BE_ALPHABETICAL = "FIRST NAME MUST BE ALPHABETICAL"; 
public static final String LAST_NAME_IS_REQUIRED = "LAST NAME IS REQUIRED"; 
public static final String LAST_NAME_IS_INVALID_LENGTH = "LAST NAME IS INVALID LENGTH"; 
public static final String LAST_NAME_MUST_BE_ALPHABETICAL = "LAST NAME MUST BE ALPHABETICAL"; 
public static final String PARAMETERS_ARE_REQUIRED = "PARAMETERS ARE REQUIRED"; 
public static final String VALIDATION_ERRORS = "VALIDATION ERRORS"; 
public static final String PARAMETERS_ARE_INVALID_FORMAT = "PARAMETERS ARE INVALID FORMAT"; 
public static final String STATE_IS_REQUIRED = "STATE IS REQUIRED"; 
public static final String STATE_IS_INVALID_LENGTH = "STATE IS INVALID LENGTH"; 
public static final String STATE_MUST_BE_ALPHABETICAL = "STATE MUST BE ALPHABETICAL"; 
public static final String COUNTRY_REQUIRED = "COUNTRY REQUIRED"; 
public static final String COUNTRY_INVALID_LENGTH = "COUNTRY INVALID LENGTH"; 
public static final String COUNTRY_MUST_BE_ALPHABETICAL = "COUNTRY MUST BE ALPHABETICAL"; 
public static final String MOBILE_NUMBER_IS_REQUIRED = "MOBILE NUMBER IS REQUIRED"; 
public static final String MOBILE_NUMBER_IS_INVALID_LENGTH = "MOBILE NUMBER IS INVALID LENGTH"; 
public static final String MOBILE_NUMBER_MUST_BE_NUMBER = "MOBILE NUMBER MUST BE NUMBER"; 
public static final String ADDRESS_IS_REQUIRED = "ADDRESS IS REQUIRED"; 
public static final String ADDRESS_IS_INVALID_LENGTH = "ADDRESS IS INVALID LENGTH"; 
public static final String ADDRESS_MUST_BE_ALPHABETICAL = "ADDRESS MUST BE ALPHABETICAL"; 
public static final String CITY_IS_REQUIRED = "CITY IS REQUIRED"; 
public static final String CITY_IS_INVALID_LENGTH = "CITY IS INVALID LENGTH"; 
public static final String CITY_MUST_BE_ALPHABETICAL = "CITY MUST BE ALPHABETICAL"; 
public static final String SALUTATION_IS_REQUIRED = "SALUTATION IS REQUIRED"; 
public static final String SALUTATION_IS_INVALID_LENGTH = "SALUTATION IS INVALID LENGTH"; 
public static final String SALUTATION_MUST_BE_ALPHABETICAL = "SALUTATION MUST BE ALPHABETICAL"; 
public static final String INVALID_DATE_FORMAT = "INVALID DATE FORMAT"; 
public static final String ROLE_NAME_REQUIRED = "ROLE NAME REQUIRED"; 
public static final String ROLE_NAME_INVALID_LENGTH = "ROLE NAME INVALID LENGTH"; 
public static final String ROLE_NOT_FOUND = "ROLE NOT FOUND"; 
public static final String ROLE_MUST_BE_ALPHABETICAL = "ROLE MUST BE ALPHABETICAL"; 
public static final String ROLE_ALREADY_EXIST = "ROLE ALREADY EXIST"; 
public static final String ALREADY_EXIST = "ALREADY EXIST"; 
public static final String REGISTRATION_DATE_IS_REQUIRED = "REGISTRATION DATE IS REQUIRED"; 
public static final String GENDER_IS_REQUIRED = "GENDER IS REQUIRED"; 
public static final String GENDER_IS_INVALID_LENGTH = "GENDER IS INVALID LENGTH"; 
public static final String GENDER_MUST_BE_ALPHABETICAL = "GENDER MUST BE ALPHABETICAL"; 
public static final String EMAIL_ID_IS_INVALID = "EMAIL ID IS INVALID"; 
public static final String USER_ID_IS_REQUIRED = "USER ID IS REQUIRED"; 
public static final String USER_ID_LENGTH_IS_INVALID = "USER ID LENGTH IS INVALID"; 
public static final String USER_ID_IS_INVALID_FORMAT = "USER ID IS INVALID FORMAT"; 
public static final String USER_ID_IS_ALREADY_EXIST = "USER ID IS ALREADY EXIST"; 
public static final String EMAIL_ID_IS_REQUIRED = "EMAIL ID IS REQUIRED"; 
public static final String EMAIL_ID_LENGTH_IS_INVALID = "EMAIL ID LENGTH IS INVALID"; 
public static final String USER_OID_IS_REQUIRED = "USER OID IS REQUIRED"; 
public static final String USER_OID_IS_INVALID_LENGTH = "USER OID IS INVALID LENGTH"; 
public static final String ROLE_OID_IS_REQUIRED = "ROLE OID IS REQUIRED"; 
public static final String ROLE_OID_LENGTH_IS_INVALID = "ROLE OID LENGTH IS INVALID"; 
public static final String MODULE_IS_REQUIRED = "MODULE IS REQUIRED"; 
public static final String MODULE_LENGTH_IS_INVALID = "MODULE LENGTH IS INVALID"; 
public static final String FLOOR_NAME_IS_REQUIRED = "FLOOR NAME IS REQUIRED"; 
public static final String FLOOR_NAME_LENGTH_IS_INVALID = "FLOOR NAME LENGTH IS INVALID"; 
public static final String FLOOR_NAME_INVALID_FORMAT = "FLOOR NAME INVALID FORMAT"; 
public static final String WARD_NAME_IS_REQUIRED = "WARD NAME IS REQUIRED"; 
public static final String WARD_NAME_LENGTH_IS_INVALID = "WARD NAME LENGTH IS INVALID"; 
public static final String WARD_NAME_INVALID_FORMAT = "WARD NAME INVALID FORMAT"; 
public static final String FLOOR_CODE_IS_REQUIRED = "FLOOR CODE IS REQUIRED"; 
public static final String FLOOR_CODE_LENGTH_IS_INVALID = "FLOOR CODE LENGTH IS INVALID"; 
public static final String FLOOR_CODE_INVALID_FORMAT = "FLOOR CODE INVALID FORMAT"; 
public static final String AUTHENTICATION_FAILED = "AUTHENTICATION FAILED"; 
public static final String PERMISSION_DENIED = "PERMISSION DENIED"; 
public static final String USERNAME_OR_PASSWORD_IS_INVALID = "USERNAME OR PASSWORD IS INVALID"; 
public static final String AUTHORITIES_NOT_FOUND = "AUTHORITIES NOT FOUND"; 
public static final String SERVICE_DENIED_FOR_IPADDRESS = "SERVICE DENIED FOR IPADDRESS"; 
public static final String SERVICE_DENIED = "SERVICE DENIED"; 
public static final String USERNAME_REQUIRED = "USERNAME REQUIRED"; 
public static final String PASSWORD_REQUIRED = "PASSWORD REQUIRED"; 
public static final String ACCOUNT_EXPIRED = "ACCOUNT EXPIRED"; 
public static final String BAD_CREDENTIALS = "BAD CREDENTIALS"; 
public static final String USER_ACCOUNT_LOCKED = "USER ACCOUNT LOCKED"; 
public static final String USER_DISABLED = "USER DISABLED"; 
public static final String USER_ACCOUNT_EXPIRED = "USER ACCOUNT EXPIRED"; 
public static final String USER_CREDENTIALS_EXPIRED = "USER CREDENTIALS EXPIRED"; 
	
	//BUSINESS ERROR END//


}
