package com.ahana.api.common;

public final class ErrorConstants {

//APPLICATION ERROR START//
public static final String SERVICE_NOT_AVAILABLE = "SERVICE NOT AVAILABLE"; 
public static final String SERVICE_NOT_ENABLED = "SERVICE NOT ENABLED"; 
public static final String SESSION_EXPIRED = "SESSION EXPIRED"; 
public static final String ACCESS_DENIED = "ACCESS DENIED"; 
public static final String GET_METHOD_NOT_SUPPORTED = "GET METHOD NOT SUPPORTED"; 
public static final String POST_METHOD_NOT_SUPPORTED = "POST METHOD NOT SUPPORTED"; 
	
	//APPLICATION ERROR END//
//SYSTEM ERROR START//
	
	//SYSTEM ERROR END//	
//BUSINESS ERROR START//
public static final String USER_NOT_FOUND = "USER NOT FOUND"; 
public static final String USER_INFORMATION_NOT_FOUND = "USER INFORMATION NOT FOUND"; 
public static final String USER_COULD_NOT_BE_SAVED = "USER COULD NOT BE SAVED"; 
public static final String UPDATE_PASSWORD_FAILED = "UPDATE PASSWORD FAILED"; 
public static final String INVALID_STATE_CODE = "INVALID STATE CODE"; 
public static final String INVALID_COUNTRY_CODE = "INVALID COUNTRY CODE"; 
public static final String NO_SEARCH_FOUND = "NO SEARCH FOUND"; 
public static final String NO_INFORMATION_FOUND_FOR_THIS_DOMAIN_OBJECT = "NO INFORMATION FOUND FOR THIS DOMAIN OBJECT"; 
public static final String INVALID_SEARCH_STRING_LENGTH = "INVALID SEARCH STRING LENGTH"; 
public static final String LOGIN_EXISTING_PASSWORD_REQUIRED = "LOGIN EXISTING PASSWORD REQUIRED"; 
public static final String LOGIN_NEW_PASSWORD_REQUIRED = "LOGIN NEW PASSWORD REQUIRED"; 
public static final String LOGIN_FORGET_PASSWORD_EMAILID_REQUIRED = "LOGIN FORGET PASSWORD EMAILID REQUIRED"; 
public static final String USER_WORKPHONE_REQUIRED = "USER WORKPHONE REQUIRED"; 
public static final String USER_TITLE_REQUIRED = "USER TITLE REQUIRED"; 
public static final String ZIPCODE_REQUIRED = "ZIPCODE REQUIRED"; 
public static final String PARENT_OID_REQUIRED = "PARENT OID REQUIRED"; 
public static final String USER_OID_REQUIRED = "USER OID REQUIRED"; 
public static final String USER_DATE_OF_BIRTH_REQUIRED = "USER DATE OF BIRTH REQUIRED"; 
public static final String USEROID_REQUIRED = "USEROID REQUIRED"; 
public static final String EMAIL_ADDRESS_REQUIRED = "EMAIL ADDRESS REQUIRED "; 
public static final String STATUS_CODE_REQUIRED = "STATUS CODE REQUIRED"; 
public static final String PASSWORD_EXPIRATION_DATE_REQUIRED = "PASSWORD EXPIRATION DATE REQUIRED"; 
public static final String LOGIN_USER_NAME_NOT_VALID = "LOGIN USER NAME NOT VALID"; 
public static final String LOGIN_NEW_PASSWORD_INVALID = "LOGIN NEW PASSWORD INVALID"; 
public static final String LOGIN_EXISTING_PASSWORD_INVALID = "LOGIN EXISTING PASSWORD INVALID"; 
public static final String LOGIN_NEW_PASSWORD_INVAILD = "LOGIN NEW PASSWORD INVAILD"; 
public static final String LOGIN_FORGET_PASSWORD_EMAILID_INVALID = "LOGIN FORGET PASSWORD EMAILID INVALID"; 
public static final String USER_WORKPHONE_INVALID_FORMATE = "USER WORKPHONE INVALID FORMATE"; 
public static final String USER_HOME_RESIDENCE_COUNTY_MUST_BE_ALPHABETICAL = "USER HOME RESIDENCE COUNTY MUST BE ALPHABETICAL"; 
public static final String USER_HOME_RESIDENCE_ZIP_INVALID_FORMAT = "USER HOME RESIDENCE ZIP INVALID FORMAT"; 
public static final String USER_WORKPHONE_INVALID_LENGTH = "USER WORKPHONE INVALID LENGTH"; 
public static final String USER_HOME_RESISDENCE_COUNTRY_INVALID_LENGTH = "USER HOME RESISDENCE COUNTRY INVALID LENGTH"; 
public static final String USER_HOME_RESISDENCE_STATE_MUST_BE_ALPHABETICAL = "USER HOME RESISDENCE STATE MUST BE ALPHABETICAL"; 
public static final String USER_HOME_RESISDENCE_STATE_INVALID_LENGTH = "USER HOME RESISDENCE STATE INVALID LENGTH"; 
public static final String USER_HOME_RESISDENCE_ZIP_INVALID_LENGTH = "USER HOME RESISDENCE ZIP INVALID LENGTH"; 
public static final String USER_STATUS_CODE_INVALID_LENGTH = "USER STATUS CODE INVALID LENGTH"; 
public static final String USER_STATUS_CODE_MUST_BE_ALPHABETICAL = "USER STATUS CODE MUST BE ALPHABETICAL"; 
public static final String USER_HOME_PHONE_INVALID_LENGTH = "USER HOME PHONE INVALID LENGTH"; 
public static final String USER_HOME_PHONE_INVALID_FORMAT = "USER HOME PHONE INVALID FORMAT"; 
public static final String USER_CELL_PHONE_INVALID_LENGTH = "USER CELL PHONE INVALID LENGTH"; 
public static final String USER_CELL_PHONE_MUST_BE_DIGITS = "USER CELL PHONE MUST BE DIGITS"; 
public static final String ADDRESS1_INVALID_LENGTH = "ADDRESS1 INVALID LENGTH"; 
public static final String USER_OID_INVALID_LENGTH = "USER OID INVALID LENGTH"; 
public static final String ZIPCODE_INVALID_LENGTH = "ZIPCODE INVALID LENGTH"; 
public static final String ZIPCODE_INVALID_FORMAT = "ZIPCODE INVALID FORMAT"; 
public static final String EMAIL_ADDRESS_MUST_BE_ALPHANUMERIC = "EMAIL ADDRESS MUST BE ALPHANUMERIC"; 
public static final String EMAIL_ADDRESS__INVALID_LENGTH = "EMAIL ADDRESS  INVALID LENGTH"; 
public static final String EMAIL_FORMAT_INVALID = "EMAIL FORMAT INVALID"; 
public static final String INVALID_EMAIL_FORMAT = "INVALID EMAIL FORMAT"; 
public static final String USER_OID_MUST_BE_ALPHANUMERIC = "USER OID MUST BE ALPHANUMERIC"; 
public static final String INVALID_PASSWORD = "INVALID PASSWORD"; 
public static final String INVALID_OLD_PASSWORD = "INVALID OLD PASSWORD"; 
public static final String INVALID_NEW_PASSWORD = "INVALID NEW PASSWORD"; 
public static final String OLD_PASSWORD_INVALID_LENGTH = "OLD PASSWORD INVALID LENGTH"; 
public static final String NEW_PASSWORD_INVALID_LENGTH = "NEW PASSWORD INVALID LENGTH"; 
public static final String LOGIN_NEW_PASSWORD_AND_VERIFY_NEW_PASSWORD_MUST_BE_SAME = "LOGIN NEW PASSWORD AND VERIFY NEW PASSWORD MUST BE SAME"; 
public static final String LOGIN_EXISTING_PASSWORD_AND_NEW_PASSWORD_MUST_BE_DIFFERENT = "LOGIN EXISTING PASSWORD AND NEW PASSWORD MUST BE DIFFERENT"; 
public static final String LOGIN_FORGET_PASSWORD_EMAILID_NOT_EXIST = "LOGIN FORGET PASSWORD EMAILID NOT EXIST"; 
public static final String LOGIN_PASSWORD_EXPIRED = "LOGIN PASSWORD EXPIRED"; 
public static final String EXISTING_USERID_INVALID = "EXISTING USERID INVALID"; 
public static final String PASSWORD_NOT_EXIST = "PASSWORD NOT EXIST"; 
public static final String USERID_ALREADY_EXISTS = "USERID ALREADY EXISTS"; 
public static final String EXISTING_USERID_AND_NEW_USERID_MUST_BE_DIFFERENT = "EXISTING USERID AND NEW USERID MUST BE DIFFERENT"; 
public static final String NEW_USERID_AND_CONFIRM_USERID_MUST_BE_SAME = "NEW USERID AND CONFIRM USERID MUST BE SAME"; 
public static final String NEW_USERID_INVALID = "NEW USERID INVALID"; 
public static final String CONFIRM_USERID_INVALID = "CONFIRM USERID INVALID"; 
public static final String OLD_PASSWORD_AND_NEW_PASSWORD_MUST_BE_DIFFERENT = "OLD PASSWORD AND NEW PASSWORD MUST BE DIFFERENT"; 
public static final String EXISTING_PASSWORD_AND_NEW_PASSWORD_MUST_BE_DIFFERENT = "EXISTING PASSWORD AND NEW PASSWORD MUST BE DIFFERENT"; 
public static final String EXISTING_PASSWORD_AND_OLD_PASSWORD_MUST_BE_SAME = "EXISTING PASSWORD AND OLD PASSWORD MUST BE SAME"; 
public static final String INVALID_START_DATE = "INVALID START DATE"; 
public static final String INVALID_END_DATE = "INVALID END DATE"; 
public static final String INVALID_START_DATE_AND_END_DATE = "INVALID START DATE AND END DATE"; 
public static final String START_DATE_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_CURRENT_DATE = "START DATE SHOULD BE LESS THAN OR EQUAL TO CURRENT DATE"; 
public static final String END_DATE_SHOULD_BE_LESS_THAN_OR_EQUAL_TO_CURRENT_DATE = "END DATE SHOULD BE LESS THAN OR EQUAL TO CURRENT DATE"; 
public static final String START_DATE_MUST_BE_LESS_THAN_OR_EQUAL_TO_END_DATE = "START DATE MUST BE LESS THAN OR EQUAL TO END DATE"; 
public static final String NO_RECORDS_FOUND = "NO RECORDS FOUND"; 
public static final String INVALID_EXTENSION = "INVALID EXTENSION"; 
public static final String OBJECT_NOT_FOUND = "OBJECT NOT FOUND"; 
public static final String USER_ID_REQUIRED = "USER ID REQUIRED"; 
public static final String USER_ID_INVALID_LENGTH = "USER ID INVALID LENGTH"; 
public static final String USER_ID_INVALID_FORMAT = "USER ID INVALID FORMAT"; 
public static final String USER_ID_ALREADY_EXIST = "USER ID ALREADY EXIST"; 
public static final String USER_TYPE_CODE_REQUIRED = "USER TYPE CODE REQUIRED"; 
public static final String USER_FIRST_NAME_REQUIRED = "USER FIRST NAME REQUIRED"; 
public static final String USER_FIRST_NAME_INVALID_LENGTH = "USER FIRST NAME INVALID LENGTH"; 
public static final String USER_FIRST_NAME_MUST_BE_ALPHABETICAL = "USER FIRST NAME MUST BE ALPHABETICAL"; 
public static final String USER_LAST_NAME_REQUIRED = "USER LAST NAME REQUIRED"; 
public static final String USER_LAST_NAME_INVALID_LENGTH = "USER LAST NAME INVALID LENGTH"; 
public static final String USER_LAST_NAME_MUST_BE_ALPHABETICAL = "USER LAST NAME MUST BE ALPHABETICAL"; 
public static final String USER_PASSWORD_REQUIRED = "USER PASSWORD REQUIRED"; 
public static final String USER_PASSWORD_INVALID_LENGTH = "USER PASSWORD INVALID LENGTH"; 
public static final String USER_STATUS_CODE_REQUIRED = "USER STATUS CODE REQUIRED"; 
public static final String PARAMETERS_ARE_REQUIRED = "PARAMETERS ARE REQUIRED"; 
public static final String USER_CREATEDBY_INVALID_LENGTH = "USER CREATEDBY INVALID LENGTH"; 
public static final String USER_UPDATEDBY_INVALID_LENGTH = "USER UPDATEDBY INVALID LENGTH"; 
public static final String VALIDATION_ERRORS = "VALIDATION ERRORS"; 
public static final String PARAMETERS_ARE_INVALID_FORMAT = "PARAMETERS ARE INVALID FORMAT"; 
public static final String INVALID_DATE = "INVALID DATE"; 
public static final String CELL_PHONE_NO_INVALID_LENGTH = "CELL PHONE NO INVALID LENGTH"; 
public static final String STATE_REQUIRED = "STATE REQUIRED"; 
public static final String STATE_INVALID_LENGTH = "STATE INVALID LENGTH"; 
public static final String COUNTRY_REQUIRED = "COUNTRY REQUIRED"; 
public static final String COUNTRY_INVALID_LENGTH = "COUNTRY INVALID LENGTH"; 
public static final String PHONE_NUMBER_REQUIRED = "PHONE NUMBER REQUIRED"; 
public static final String PHONE_NUMBER_INVALID_LENGTH = "PHONE NUMBER INVALID LENGTH"; 
public static final String COUNTRY_MUST_BE_ALPHABETICAL = "COUNTRY MUST BE ALPHABETICAL"; 
public static final String ZIP_CODE_REQUIRED = "ZIP CODE REQUIRED"; 
public static final String ZIP_CODE_INVALID_LENGTH = "ZIP CODE INVALID LENGTH"; 
public static final String DATE_OF_BIRTH_REQUIRED = "DATE OF BIRTH REQUIRED"; 
public static final String ADDRESS_REQUIRED = "ADDRESS REQUIRED"; 
public static final String CITY_REQUIRED = "CITY REQUIRED"; 
public static final String CITY_INVALID_LENGTH = "CITY INVALID LENGTH"; 
public static final String SALUTATION_REQUIRED = "SALUTATION REQUIRED"; 
public static final String SALUTATION_INVALID_LENGTH = "SALUTATION INVALID LENGTH"; 
public static final String INVALID_DATE_FORMAT = "INVALID DATE FORMAT"; 
public static final String CELL_PHONE_NO_REQUIRED = "CELL PHONE NO REQUIRED"; 
public static final String ROLE_NAME_REQUIRED = "ROLE NAME REQUIRED"; 
public static final String ROLE_NAME_INVALID_LENGTH = "ROLE NAME INVALID LENGTH"; 
public static final String ROLE_NOT_FOUND = "ROLE NOT FOUND"; 
public static final String ROLE_MUST_BE_ALPHABETICAL = "ROLE MUST BE ALPHABETICAL"; 
public static final String ROLE_ALREADY_EXIST = "ROLE ALREADY EXIST"; 
public static final String ALREADY_EXIST = "ALREADY EXIST"; 
public static final String AUTHENTICATION_FAILED = "AUTHENTICATION FAILED"; 
public static final String PERMISSION_DENIED = "PERMISSION DENIED"; 
public static final String USERNAME_OR_PASSWORD_IS_INVALID = "USERNAME OR PASSWORD IS INVALID"; 
public static final String AUTHORITIES_NOT_FOUND = "AUTHORITIES NOT FOUND"; 
public static final String SERVICE_DENIED_FOR_IPADDRESS = "SERVICE DENIED FOR IPADDRESS"; 
public static final String SERVICE_DENIED = "SERVICE DENIED"; 
public static final String USERNAME_REQUIRED = "USERNAME REQUIRED"; 
public static final String PASSWORD_REQUIRED = "PASSWORD REQUIRED"; 
public static final String ACCOUNT_EXPIRED = "ACCOUNT EXPIRED"; 
public static final String BAD_CREDENTIALS = "BAD CREDENTIALS"; 
public static final String USER_ACCOUNT_LOCKED = "USER ACCOUNT LOCKED"; 
public static final String USER_DISABLED = "USER DISABLED"; 
public static final String USER_ACCOUNT_EXPIRED = "USER ACCOUNT EXPIRED"; 
public static final String USER_CREDENTIALS_EXPIRED = "USER CREDENTIALS EXPIRED"; 
	
	//BUSINESS ERROR END//


}
